### PR TITLE
api/auth: fix invalid mgo session

### PR DESCRIPTION
**Pull request by babygoat**
Address [twreporter-85](https://twreporter-org.atlassian.net/browse/TWREPORTER-85)

### CODE REVIEW

**Comment by babygoat** [comment]
The test was failing due to the URL change: e0bc81a. It can be resolved once the test commit is squashed.

**Comment by babygoat** [comment]
The simulation environment can be set up by the [change](https://github.com/twreporter/environment-setup/pull/17)

**Review by Aylie-Chou — APPROVED** [review]
LGTM

**Comment by babygoat** [comment]
@Aylie-Chou  I rebased and squashed the temporal commit for validation. Also, I [removed](https://github.com/twreporter/go-api/pull/434/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L54) the unused package totally and [updated the package to the proper version](https://github.com/twreporter/go-api/pull/434/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L17) instead of the latest buggy version to fix the test. Let me know if you have any consideration for that.

**Pull request merged**
