### PR TITLE
Fix linepay notify format error

### PR DESCRIPTION
**Pull request by babygoat**

### CODE REVIEW

**Comment by nickhsine** [comment]
LGTM.
Minor. Is this change a breaking change? Not just a bug fix? 
Would this change affect clients(support.twreporter.org)?

**Comment by babygoat** [comment]
> LGTM.
> Minor. Is this change a breaking change? Not just a bug fix?
> Would this change affect clients(support.twreporter.org)?

Nope. But the request post body of route `/v1/donations/line-notify` is fixed. Does this just stand for the patch version update?

**Comment by nickhsine** [comment]
> > LGTM.
> > Minor. Is this change a breaking change? Not just a bug fix?
> > Would this change affect clients(support.twreporter.org)?
> 
> Nope. But the request post body of route `/v1/donations/line-notify` is fixed. Does this just stand for the patch version update?
If this change doesn't affect clients,
I think we could bump patch version.

**Comment by babygoat** [comment]
I got ur point. The public endpoint serves no change from API document but incorrect implementation. That should be a patch update.

**Comment by babygoat** [comment]
Updated.

**Comment by nickhsine** [comment]
LGTM

**Pull request merged**
