### PR TITLE
Update go vendor package version

### PR DESCRIPTION
**Pull request by babygoat**
This patch updates the go vendor package to the lastest commit. Majorly
, the changes are to adopt the fix in gorm@1.9.2.

### CODE REVIEW

**Comment by babygoat** [comment]
@nickhsine 

There are two problems for the changes. 
1. gorm@1.9.2 requires sync.Map (concurrent-safe data structure) in go 1.9.0^. We will be required to upgrade the CI images for the go versions.
2.  glide lacks of the specific package upgrade until now.  I suggest moving forward to go module in replace of glide.

I would like to know the comments from you.

**Comment by nickhsine** [comment]
@babygoat The circle build is failing. Please help to check the problem.

**Comment by nickhsine** [comment]
Could we update `glide.yaml` instead of updating `glide.lock` which is a automatically generated by `glide`?

**Comment by babygoat** [comment]
Please see my comment.
The error results from bullet 1. I'd like to know if you have any concerns of that.

**Comment by babygoat** [comment]
> Could we update `glide.yaml` instead of updating `glide.lock` which is a automatically generated by `glide`?

Please see my bullet 2.
Sure. However, there's a lot of versions need to fix in glide.yaml if we'd like to adopt changes. 
If we'd like to upgrade the go environment now, my suggestion was also introduce the `go mod` instead of `glide` in 1.11 which might have better package management (e.g, single package upgrade commands or options.

**Comment by nickhsine** [comment]
> > Could we update `glide.yaml` instead of updating `glide.lock` which is a automatically generated by `glide`?
> 
> Please see my bullet 2.
> Sure. However, there's a lot of versions need to fix in glide.yaml if we'd like to adopt changes.
> If we'd like to upgrade the go environment now, my suggestion was also introduce the `go mod` instead of `glide` in 1.11 which might have better package management (e.g, single package upgrade commands or options.

Sure, we could upgrade to  `go@1.11`.
However, it takes time. 
We might need to plan it.

In order to solve this dependency update, how about updating `glide.yaml` first? 
`gorm@^1.0.0` -> `gorm@^1.9.2` ?

For bullet 1, I have built a new [docker image circle-ci-go:1.10-alpine3.8](https://cloud.docker.com/u/thereporter/repository/docker/thereporter/circleci-go-api).

May we use that image to address this problem at this time?

**Comment by babygoat** [comment]
Updated.

**Comment by nickhsine** [comment]
LGTM

**Pull request merged**
